version: "3"
services:
  nginx:
    # replace username/repo:tag with your name and image details
    image: nginx
    depends_on:
      - mongo
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:80"
    networks:
      - mongonet
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mongonet
networks:
  mongonet:
